# Generated by Django 2.2.5 on 2021-04-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('strategy', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('mitigation', models.BooleanField(blank=True, null=True)),
                ('adaptation', models.BooleanField(blank=True, null=True)),
                ('stance', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Support'), (2, 'Oppose'), (3, 'Ignore')], null=True)),
                ('effort', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('house', models.PositiveSmallIntegerField(choices=[(1, 'Senate'), (2, 'Assembly')])),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('letter_due_date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('bills', models.ManyToManyField(to='legislation.Bill')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Committee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Session')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.Sector'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('people', models.ManyToManyField(to='legislation.Person')),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.CreateModel(
            name='SupportLetter',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('letter_due_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Bill')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Hearing')),
                ('volunteers', models.ManyToManyField(to='legislation.Person')),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.AddField(
            model_name='sector',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.Team'),
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Bill')),
            ],
            bases=('legislation.basemodel',),
        ),
        migrations.CreateModel(
            name='BillAmendment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='legislation.BaseModel')),
                ('description', models.TextField(blank=True, null=True)),
                ('importance', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Bill')),
            ],
            bases=('legislation.basemodel',),
        ),
    ]
