# Generated by Django 2.2.5 on 2021-04-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.PositiveSmallIntegerField(choices=[(1, 'Senate'), (2, 'Assembly')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.Hearing')),
            ],
        ),
    ]
