# Generated by Django 2.2.5 on 2021-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_auto_20210418_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(default='CA', max_length=100),
        ),
    ]
