# Generated by Django 2.2.5 on 2021-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0003_auto_20210418_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
