# Generated by Django 2.2.5 on 2021-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0004_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='house',
            field=models.CharField(choices=[('Senate', 'Senate'), ('Assembly', 'Assembly')], default='Assembly', max_length=100),
        ),
    ]
