# Generated by Django 2.2.5 on 2021-04-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0005_auto_20210418_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legislation.Session'),
            preserve_default=False,
        ),
    ]
