# Generated by Django 2.2.5 on 2021-04-18 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0006_bill_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='billamendment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
