# Generated by Django 2.2.5 on 2021-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0007_billamendment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='letter_date_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
