# Generated by Django 2.2.5 on 2021-04-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0009_auto_20210418_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
