# Generated by Django 2.2.5 on 2021-04-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0010_auto_20210418_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportletter',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
