# Generated by Django 2.2.5 on 2021-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0011_supportletter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='letter_due_date',
            field=models.DateField(null=True),
        ),
    ]
