# Generated by Django 2.2.5 on 2021-04-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0012_auto_20210427_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
