# Generated by Django 2.2.5 on 2021-04-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0013_auto_20210427_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
