# Generated by Django 2.2.5 on 2021-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0014_auto_20210427_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportletter',
            name='letter_date_confirmed',
        ),
        migrations.AddField(
            model_name='supportletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supportletter',
            name='letter_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportletter',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='legislation.Person'),
        ),
    ]
