# Generated by Django 2.2.5 on 2021-06-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0016_supportletter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alternate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.PositiveIntegerField()),
                ('webpage', models.URLField(blank=True, null=True)),
                ('party', models.CharField(blank=True, choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], max_length=25, null=True)),
                ('capitol_office', models.CharField(max_length=200, null=True)),
                ('district_office', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
