# Generated by Django 2.2.2 on 2021-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0016_supportletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supportletter',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
