# Generated by Django 2.2.2 on 2021-06-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0017_auto_20210613_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportletter',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
