# Generated by Django 2.2.5 on 2021-06-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0017_legislator'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='contact',
            field=models.URLField(blank=True, null=True),
        ),
    ]
