# Generated by Django 3.2.3 on 2022-02-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0018_auto_20210613_2343'),
        ('legislation', '0018_legislator_contact'),
    ]

    operations = [
    ]
