# Generated by Django 3.2.3 on 2022-02-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0019_merge_0018_auto_20210613_2343_0018_legislator_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='follows',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
