# Generated by Django 3.2.3 on 2022-03-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0022_auto_20220330_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='letter_time',
            field=models.CharField(default='noon', max_length=20),
        ),
    ]
