# Generated by Django 2.1 on 2018-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='unpublishedstatus',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'in preparation'), (1, 'under review'), (2, 'published')], default=2),
        ),
    ]
