# Generated by Django 2.1.7 on 2019-08-27 05:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20190826_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('block0', ckeditor.fields.RichTextField()),
                ('block1', ckeditor.fields.RichTextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='')),
                ('file4', models.FileField(blank=True, null=True, upload_to='')),
                ('file5', models.FileField(blank=True, null=True, upload_to='')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='person',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
