# Generated by Django 2.1.7 on 2019-08-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20190826_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'last_modified'},
        ),
    ]
