# Generated by Django 2.1.7 on 2019-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20190826_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='peerreviewed',
            field=models.BooleanField(default=True),
        ),
    ]
