# Generated by Django 6.0 on 2025-12-26 08:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_article_peerreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='block0',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='block1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
